export const SET_WORKER_INFO = "SET_WORKER_INFO";
export const GET_JOB_MATCHES = "GET_JOB_MATCHES";
export const ACCEPT_JOB = "ACCEPT_JOB";
export const REJECT_OR_ACCEPT_JOB = "REJECT_OR_ACCEPT_JOB";
export const DISPLAY_JOB_MESSAGE = "DISPLAY_JOB_MESSAGE";
